name: Update inputs

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update_inputs:
    name: Update inputs
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Update inputs
        run: |
          nix flake update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update flake inputs"
          branch: "update-flake-inputs"
          delete-branch: true
          labels: |
            chore
            inputs
            automated
